version: "3.7"
services:
  datalake:
    image: "postgres:15.1"
    ports:
      - "5432:5432"
    volumes:
      - "pgdata:/var/lib/postgresql/data"
      - "./sql:/docker-entrypoint-initdb.d"
    environment:
      POSTGRES_PASSWORD: "wallaceEhLindo"
      TZ: "America/Recife"

volumes:
  pgdata: